language: node_js
node_js:
- '0.11'
addons:
  code_climate:
    repo_token: bd56f54b4cdb134373804a53ea6d108a220dae8710e902614fbce35c1a0e
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: j/yUf7bTIqAw+tZMLuuif5wIBkhrmom6V+u+iVaXpzrzJRxjfeTZ3jIxf3kKJBhGPQ5LIBTnBk7jRsCOdnTizMuzsfZ8Qmn0LW3/PpjgrtKZUEAnMTluXIT8PCZMeDG4tBwkGw1YdCG5qyw/sF6AHfLbl/AAj4Krc85cfW+8Os0oGAfXzuzpRhGIpKHqh6pMgvKgFYryYaYs4o+2bmyTnR7+BlsN6Ec6w7FLDxqRL8Ew/s2bvo1zNrG7gVKyUBgNRjg3l8bq58D9buKWCeYnyCPFckCwxChYTqLrtT1oXU1DKT4nImXxQIr1vKygk4gCFvHhYuum0mSZRA9Dj66+SAP8eEtvTI1iXh51dkfEUY5QBkfZqECC22kDpqXE+fqo5B7PETH06bQ/TRyPU0Pv5PNNLd1a9kXd32zxp4nvGWdq6+svVRqi4WydW2aYnj1k20Au2OdDiQFaOemwKcpxb4HMOko+K7CR3e2t5Tz/Y0Dxmv5QbvZkDwF0R/VyfNUN5lkdRqu08DJqzIJVULZ3Aw397Cx75mFwM5u95ZCU5TpG/+kZqBHKhsfzodKz2ox8vsraWsKV1hgYnYc8Q+FGGSqd17grr9TREOdLC6MkyzGufgURqn2z3/7oNOmGcRMYNzjH1ti1pC7b+7TWuww3QC+aXZHkqJY+mMCMdtIYMX8=
  on:
    tags: true
    branches: true
branches:
  only:
  - "/^v[0-9]/"
after_success:
- npm run coverage
- bash <(curl -s https://codecov.io/bash)
